Create View vsan01 
      ( sanann,
        ciecle,
        cptcle,
        unacle,
        sanusrapp,
        sanbdgann,
        sanbdg1,
        sanbdg2,
        sanbdg3,
        sanbdg4,
        sanbdg5,
        sanbdg6,
        sanbdg7,
        sanbdg8,
        sanbdg9,
        sanbdg10,
        sanbdg11,
        sanbdg12,
        sanbdg13,
        sanbdg14,
        sanbdgrevann,
        sanbdgrev1,
        sanbdgrev2,
        sanbdgrev3,
        sanbdgrev4,
        sanbdgrev5,
        sanbdgrev6,
        sanbdgrev7,
        sanbdgrev8,
        sanbdgrev9,
        sanbdgrev10,
        sanbdgrev11,
        sanbdgrev12,
        sanbdgrev13,
        sanbdgrev14,
        sansldouveng,
        sancumeng1,
        sancumeng2,
        sancumeng3,
        sancumeng4,
        sancumeng5,
        sancumeng6,
        sancumeng7,
        sancumeng8,
        sancumeng9,
        sancumeng10,
        sancumeng11,
        sancumeng12,
        sancumeng13,
        sancumeng14,
        sancumanneng1,
        sancumanneng2,
        sancumanneng3,
        sancumanneng4,
        sancumanneng5,
        sancumanneng6,
        sancumanneng7,
        sancumanneng8,
        sancumanneng9,
        sancumanneng10,
        sancumanneng11,
        sancumanneng12,
        sancumanneng13,
        sancumanneng14,
        sansldouv,
        sancumree1,
        sancumree2,
        sancumree3,
        sancumree4,
        sancumree5,
        sancumree6,
        sancumree7,
        sancumree8,
        sancumree9,
        sancumree10,
        sancumree11,
        sancumree12,
        sancumree13,
        sancumree14,
        sancumann1,
        sancumann2,
        sancumann3,
        sancumann4,
        sancumann5,
        sancumann6,
        sancumann7,
        sancumann8,
        sancumann9,
        sancumann10,
        sancumann11,
        sancumann12,
        sancumann13,
        sancumann14 )
As
 Select san.sanann,
        san.ciecle,
        san.cptcle,
        san.unacle,
        san.sanusrapp,
        san.sanbdgann,
        san.sanbdg1,
        san.sanbdg2,
        san.sanbdg3,
        san.sanbdg4,
        san.sanbdg5,
        san.sanbdg6,
        san.sanbdg7,
        san.sanbdg8,
        san.sanbdg9,
        san.sanbdg10,
        san.sanbdg11,
        san.sanbdg12,
        san.sanbdg13,
        san.sanbdg14,
        san.sanbdgrevann,
        san.sanbdgrev1,
        san.sanbdgrev2,
        san.sanbdgrev3,
        san.sanbdgrev4,
        san.sanbdgrev5,
        san.sanbdgrev6,
        san.sanbdgrev7,
        san.sanbdgrev8,
        san.sanbdgrev9,
        san.sanbdgrev10,
        san.sanbdgrev11,
        san.sanbdgrev12,
        san.sanbdgrev13,
        san.sanbdgrev14,
        san.sansldouveng,
        san.sancumeng1,
        san.sancumeng2,
        san.sancumeng3,
        san.sancumeng4,
        san.sancumeng5,
        san.sancumeng6,
        san.sancumeng7,
        san.sancumeng8,
        san.sancumeng9,
        san.sancumeng10,
        san.sancumeng11,
        san.sancumeng12,
        san.sancumeng13,
        san.sancumeng14,
        ( san.sancumree1 ),
        ( san.sancumree1 + san.sancumree2 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9 + san.sancumree10 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9 + san.sancumree10 + san.sancumree11 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9 + san.sancumree10 + san.sancumree11 + san.sancumree12 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9 + san.sancumree10 + san.sancumree11 + san.sancumree12 +
          san.sancumree13 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9 + san.sancumree10 + san.sancumree11 + san.sancumree12 +
          san.sancumree13 + san.sancumree14 ),
        san.sansldouv,
        san.sancumree1,
        san.sancumree2,
        san.sancumree3,
        san.sancumree4,
        san.sancumree5,
        san.sancumree6,
        san.sancumree7,
        san.sancumree8,
        san.sancumree9,
        san.sancumree10,
        san.sancumree11,
        san.sancumree12,
        san.sancumree13,
        san.sancumree14,
        ( san.sancumree1 ),
        ( san.sancumree1 + san.sancumree2  ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3  ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4  ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5  ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6  ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7  ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8  ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9  ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9 + san.sancumree10 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9 + san.sancumree10 + san.sancumree11 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9 + san.sancumree10 + san.sancumree11 + san.sancumree12 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9 + san.sancumree10 + san.sancumree11 + san.sancumree12 +
          san.sancumree13 ),
        ( san.sancumree1 + san.sancumree2 + san.sancumree3 + san.sancumree4 +
          san.sancumree5 + san.sancumree6 + san.sancumree7 + san.sancumree8 +
          san.sancumree9 + san.sancumree10 + san.sancumree11 + san.sancumree12 +
          san.sancumree13 + san.sancumree14 )
   From mcsolde_annuel san;
